TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

ARCHIVE += sioc-li21-im01.archive
ARCHIVE += sioc-li21-im02.archive
ARCHIVE += sioc-li24-im01.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
