##############################################################################
## This file is part of 'LCLS2 Common Carrier Core'.
## It is subject to the license terms in the LICENSE.txt file found in the
## top-level directory of this distribution and at:
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
## No part of 'LCLS2 Common Carrier Core', including this file,
## may be copied, modified, propagated, or distributed except according to
## the terms contained in the LICENSE.txt file.
##############################################################################
#schemaversion 3.0.0
#once DspCoreConfigMr.yaml

DspCoreConfigMr: &DspCoreConfigMr
  description: "Sysgen configuration registers"
  class: MMIODev
  configPrio: 1
  size: 0x010000
  #########
  children:
  #########
    #########################################################
    Version:
      class: IntField
      at:
        offset: 0x0000
      sizeBits: 32
      mode: RO
      description: "System generator core version"
    #########################################################
    Inp0CoefA0:
      class: IntField
      at:
        offset: 0x0004
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 0 Coef A0 of processig equation to properly scale the first averaged group"
    #########################################################
    Inp0CoefA1:
      class: IntField
      at:
        offset: 0x0008
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 0 Coef A1 of processig equation to properly scale the second averaged group"
    #########################################################
    Inp0CoefA2:
      class: IntField
      at:
        offset: 0x000C
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 0 Coef A2 of processig equation to properly scale the third averaged group"
    #########################################################
    Inp0Coef_offset:
      class: IntField
      at:
        offset: 0x0010
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 0 offset value if needed"
    #########################################################
    Inp1CoefA0:
      class: IntField
      at:
        offset: 0x0014
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 1 Coef A0 of processig equation to properly scale the first averaged group"
    #########################################################
    Inp1CoefA1:
      class: IntField
      at:
        offset: 0x0018
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 1 Coef A1 of processig equation to properly scale the second averaged group"
    #########################################################
    Inp1CoefA2:
      class: IntField
      at:
        offset: 0x001C
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 1 Coef A2 of processig equation to properly scale the third averaged group"
    #########################################################
    Inp1Coef_offset:
      class: IntField
      at:
        offset: 0x0020
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 2 offset value if needed"
    #########################################################
    Inp2CoefA0:
      class: IntField
      at:
        offset: 0x0024
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 2 Coef A0 of processig equation to properly scale the first averaged group"
    #########################################################
    Inp2CoefA1:
      class: IntField
      at:
        offset: 0x0028
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 2 Coef A1 of processig equation to properly scale the second averaged group"
    #########################################################
    Inp2CoefA2:
      class: IntField
      at:
        offset: 0x002C
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 2 Coef A2 of processig equation to properly scale the third averaged group"
    #########################################################
    Inp2Coef_offset:
      class: IntField
      at:
        offset: 0x0030
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating - Input 2 offset value if needed"
    #########################################################
    Inp01Thresh:
      class: IntField
      at:
        offset: 0x0034
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating -  threshold for input 0 and 1 charge"
    #########################################################
    Inp01DiffThresh:
      class: IntField
      at:
        offset: 0x0038
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating -  threshold for difference between input 0 and 1 charge"
    #########################################################
    Inp10DiffThresh:
      class: IntField
      at:
        offset: 0x003C
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating -  threshold for difference between input 1 and 0 charge"
    #########################################################
    Inp02DiffThresh:
      class: IntField
      at:
        offset: 0x0040
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating -  threshold for difference between input 0 and 2 charge"
    #########################################################
    Inp20DiffThresh:
      class: IntField
      at:
        offset: 0x0044
      encoding: IEEE_754
      sizeBits: 32
      mode: RW
      description: "Floating -  threshold for difference between input 2 and 0 charge"
    #########################################################


